# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cb310808502082f7acf7f75cac7d87578635129510d669f322406abed7d1c05ae2671f011feb54e3ca554a52a7518189343ceb0615b54dca83225df8b35dfa4

test:
  secret_key_base: f87ac90f450d97efff764a43d6601d77eaa3ce8603cee09db5c2cc6a7c3532c1bea2a09c14b3ffce49557a1e7280aed3ec549714d4605420ca8974cdc5caf5a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
